routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        //instructions

        Route::get('instructors', 'AdminController@instructors_index')->name('instructors.index');

        Route::get('instructors/create', 'AdminController@instructors_create')->name('instructors.create');

        Route::get('instructors/edit', 'AdminController@instructors_edit')->name('instructors.edit');

        Route::post('instructors/save', 'AdminController@instructors_save')->name('instructors.save');

        Route::get('instructors/view', 'AdminController@instructors_view')->name('instructors.view');

        Route::get('instructors/delete', 'AdminController@instructors_delete')->name('instructors.delete');

        Route::get('instructors/status', 'AdminController@instructors_status')->name('instructors.status');

        Route::get('instructors/verify', 'AdminController@instructors_verify_status')->name('instructors.verify');

        //sub instructor routes
        Route::get('sub_instructors/create','AdminController@sub_instructors_create')->name('sub_instructors.create');

        Route::post('sub_instructors/save','AdminController@sub_instructors_save')->name('sub_instructors.save');

        Route::get('sub_instructors/delete','AdminController@sub_instructors_delete')->name('sub_instructors.delete');

        //sub instructor subscription
        Route::get('instructor/subscriptions','AdminController@instructors_subscriptions_index')->name('instructors.subscriptions_index');

        Route::post('instructor/subscription_payments','AdminController@instructors_subscriptions_payments')->name('instructors.subscriptions_payments');

        Route::get('instructor/subscriptions_payments/delete','AdminController@instructors_subscriptions_payments_delete')->name('instructors.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        // rooms crud
        Route::get('rooms', 'AdminController@rooms_index')->name('rooms.index');

        Route::get('rooms/create', 'AdminController@rooms_create')->name('rooms.create');

        Route::get('rooms/edit', 'AdminController@rooms_edit')->name('rooms.edit');

        Route::post('rooms/save', 'AdminController@rooms_save')->name('rooms.save');

        Route::get('rooms/view', 'AdminController@rooms_view')->name('rooms.view');

        Route::get('rooms/delete', 'AdminController@rooms_delete')->name('rooms.delete');

        Route::get('rooms/status', 'AdminController@rooms_status')->name('rooms.status');

        //rooms users create
        Route::get('rooms/user/create','AdminController@rooms_user_create')->name('rooms.user.create');

        Route::post('rooms/users/save','AdminController@rooms_user_save')->name('rooms.user.save');

        Route::get('rooms/users/delete','AdminController@rooms_user_delete')->name('rooms.user.delete');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');
    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\AdminLoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Instructor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Setting;

class Instructor extends Model
{
    protected $fillable = ['email', 'password'];

    protected $hidden = ['id'];

    protected $appends = ['instructor_id', 'instructor_unique_id'];

    public function getInstructorIdAttribute() {

        return $this->id;
    }

    public function getInstructorUniqueIdAttribute() {

        return $this->unique_id;
    }

    public function instructorRooms() {

    	return $this->hasMany(Room::class,'instructor_id');
    }

    public function subInstructors() {

    	return $this->hasMany(SubInstructor::class,'sub_instructor_id');
    }

    public function subInstructorDetails() {

        return $this->hasMany(SubInstructor::class,'instructor_id');
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeProfileResponse($query) {

        return $query->select('instructors.*');
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSubInstructorResponse($query) {

        return $query->select(
                'instructors.id',
                'instructors.unique_id',
                'instructors.unique_id as sub_instructor_unique_id', 
                'instructors.name', 
                'instructors.first_name', 
                'instructors.last_name', 
                'instructors.email', 
                'instructors.mobile', 
                'instructors.picture', 
                'instructors.id as sub_instructor_id'
            );
    
    }
      
    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            }

            $model->attributes['payment_mode'] = COD;

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = \Helper::generate_token();

            $model->attributes['token_expiry'] = \Helper::generate_token_expiry();

            $model->attributes['status'] = INSTRUCTOR_APPROVED;

            if(in_array($model->attributes['login_by'], ['facebook', 'google', 'apple', 'linkedin', 'instagram'] )) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['username'] = $model->attributes['unique_id'] = "INS"."-".$model->attributes['id'].routefreestring($model->attributes['name']);

            $model->save();
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = $model->attributes['unique_id'] = "INS"."-".$model->attributes['id'].routefreestring($model->attributes['name']);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            $model->instructorRooms()->delete();

            $model->subInstructors()->delete();

        });

    }
}

resources/views/admin/instructors/_form.blade.php
<div class="row">

    <div class="col-12">

        <div class="card card-navy card-outline">

            <div class="card-header">
                
                <h4 class="text-uppercase">
                    {{$instructor_details->id ? tr('edit_instructor') : tr('add_instructor')}}
                    <a class="btn btn-outline-success pull-right" href="{{route('admin.instructors.index')}}"> <i class="fa fa-eye"></i> {{tr('view_instructors')}} </a>
                </h4>
            </div>

            <form class="forms-sample" action="{{ Setting::get('is_demo_control_enabled') == NO ? route('admin.instructors.save') : '#'}}" method="POST" enctype="multipart/form-data" role="form">
                @csrf

                <div class="card-body">
                    @if($instructor_details->id)

                    <input type="hidden" name="instructor_id" id="instructor_id" value="{{$instructor_details->id}}" />

                    @endif

                    <input type="hidden" name="login_by" id="login_by" value="{{$instructor_details->login_by ?: 'manual'}}" />

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="name">{{ tr('name') }} <span class="admin-required">*</span> </label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="{{ tr('name') }}" value="{{ old('name') ?: $instructor_details->name}}" required />
                        </div>

                        <div class="form-group col-md-6">
                            <label for="mobile">{{ tr('mobile') }} </label>

                            <input type="number" class="form-control" pattern="[0-9]{6,13}" id="mobile" name="mobile" placeholder="{{ tr('mobile') }}" value="{{ old('mobile') ?: $instructor_details->mobile}}" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="email">{{ tr('email')}} <span class="admin-required">*</span></label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="{{ tr('email')}}" value="{{ old('email') ?: $instructor_details->email}}" required />
                        </div>

                        @if(!$instructor_details->id)

                        <div class="form-group col-md-6">
                            <label for="password">{{ tr('password') }} <span class="admin-required">*</span></label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="{{ tr('password') }}" value="{{old('password')}}" required title="{{ tr('password_notes') }}" />
                        </div>

                        @endif
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>{{tr('upload_image')}}</label>

                            <div class="input-group col-xs-12">
                                <input type="file" class="form-control file-upload-info" name="picture" placeholder="{{tr('upload_image')}}" accept="image/*" />

                                <div class="input-group-append">
                                    <button class="btn btn-info" type="button">{{tr('upload')}}</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="reset" class="btn btn-light">{{ tr('reset')}}</button>

                    @if(Setting::get('is_demo_control_enabled') == NO )

                    <button type="submit" class="btn btn-success mr-2">{{ tr('submit') }}</button>

                    @else

                    <button type="button" class="btn btn-success mr-2" disabled>{{ tr('submit') }}</button>

                    @endif
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/instructors/create.blade.php
@extends('layouts.admin') 

@section('content-header', tr('instructors'))

@section('bread-crumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.instructors.index') }}">{{tr('instructors')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_instructor')}}</span>
    </li>
           
@endsection 

@section('content') 

	@include('admin.instructors._form') 

@endsection

resources/views/admin/instructors/edit.blade.php
@extends('layouts.admin')

@section('content-header', tr('instructors'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.instructors.index') }}">{{tr('instructors')}}</a></li>
    
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{ tr('edit_instructor') }}</span>
    </li>
           
@endsection 

@section('content')

	@include('admin.instructors._form')

@endsection

resources/views/admin/instructors/index.blade.php
@extends('layouts.admin') 

@section('content-header', tr('instructors'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.instructors.index')}}">{{tr('instructors')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('view_instructors') }}</span>
    </li> 
           
@endsection 

@section('content')

<div class="row">

    <div class="col-12">

        <div class="card card card-navy card-outline">

            <div class="card-header">

                <h4 class="text-uppercase">{{tr('view_instructors')}}
                    <a class="btn btn-outline-success pull-right" href="{{route('admin.instructors.create')}}">
                        <i class="fa fa-plus"></i> {{tr('add_instructor')}}
                    </a>
                </h4>

            </div>

            <div class="card-body">

                <form  action="{{route('admin.instructors.index')}}" method="GET" role="search">

                    <div class="row">

                        <div class="col-3">
                            @if(Request::has('search_key'))
                                <p class="text-muted">Search results for <b>{{Request::get('search_key')}}</b></p>
                            @endif
                        </div>

                        <div class="col-3">

                            <select class="form-control select2" name="status">

                                <option  class="select-color" value="">{{tr('select_status')}}</option>

                                <option  class="select-color" value="{{SORT_BY_APPROVED}}">{{tr('approved')}}</option>

                                <option  class="select-color" value="{{SORT_BY_DECLINED}}">{{tr('declined')}}</option>

                                <option  class="select-color" value="{{SORT_BY_EMAIL_VERIFIED}}">{{tr('verified')}}</option>

                                <option  class="select-color" value="{{SORT_BY_EMAIL_NOT_VERIFIED}}">{{tr('un_verified')}}</option>

                            </select>

                        </div>

                        <div class="col-6">

                            <div class="input-group">
                                <input type="text" class="form-control search-input" name="search_key"
                                    placeholder="{{tr('instructors_search_placeholder')}}"> <span class="input-group-btn">
                                    &nbsp

                                    <button type="submit" class="btn btn-default">
                                       <i class="fa fa-search" aria-hidden="true"></i>
                                    </button>

                                    <a class="btn btn-default" href="{{route('admin.instructors.index')}}"><i class="fa fa-eraser" aria-hidden="true"></i>
                                    </a>
                                </span>
                            </div>

                        </div>

                    </div>

                </form>

                <table id="table_order" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('name')}}</th>
                            <th>{{tr('email')}}</th>
                            <th>{{tr('mobile')}}</th>
                            <th>{{tr('rooms')}}</th>
                            <th>{{tr('status')}}</th>
                            <th>{{tr('verify')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($instructors as $i => $instructor_details)
                              
                            <tr>
                                <td>{{$i+$instructors->firstItem()}}</td>

                                <td>
                                    <a href="{{route('admin.instructors.view' , ['instructor_id' => $instructor_details->id])}}"> {{ $instructor_details->name }}
                                    </a>
                                </td>

                                <td> {{ $instructor_details->email }} </td>

                                <td> {{ $instructor_details->mobile ?: tr('unavailable') }} </td>

                                <td><a href="{{route('admin.rooms.index',['instructor_id' =>$instructor_details->id])}}">{{$instructor_details->instructorRooms()->count()}}</a></td>

                                <td>

                                    @if($instructor_details->status == APPROVED)

                                        <span class="badge bg-success">{{ tr('approved') }} </span>

                                    @else

                                        <span class="badge bg-danger">{{ tr('declined') }} </span>

                                    @endif

                                </td>

                                <td>   

                                    @if($instructor_details->is_verified == INSTRUCTOR_EMAIL_VERIFIED) 

                                        <span class="badge bg-success">{{ tr('verified') }} </span>

                                    @else

                                        <a class="badge bg-info" href="{{ route('admin.instructors.verify', ['instructor_id' => $instructor_details->id]) }}"> 
                                            {{ tr('verify') }} 
                                        </a>

                                    @endif  
                                                                  
                                </td>

                                <td>     

                                    <div class="template-demo">

                                        <div class="dropdown">

                                            <button class="btn btn-outline-primary  dropdown-toggle" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                {{tr('action')}}
                                            </button>

                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">
                                              
                                                <a class="dropdown-item" href="{{ route('admin.instructors.view', ['instructor_id' => $instructor_details->id]) }}">
                                                    {{tr('view')}}
                                                </a>
                                                
                                                @if(Setting::get('is_demo_control_enabled') == NO)
                                                    <a class="dropdown-item" href="{{ route('admin.instructors.edit', ['instructor_id' => $instructor_details->id]) }}">
                                                        {{tr('edit')}}
                                                    </a>
                                                    
                                                    <a class="dropdown-item" href="{{route('admin.instructors.delete', ['instructor_id' => $instructor_details->id])}}" 
                                                    onclick="return confirm(&quot;{{tr('instructor_delete_confirmation' , $instructor_details->name)}}&quot;);">
                                                        {{tr('delete')}}
                                                    </a>
                                                @else

                                                    <a class="dropdown-item text-muted" href="javascript:;">{{tr('edit')}}</a>
                                                  
                                                    <a class="dropdown-item text-muted" href="javascript:;">{{tr('delete')}}</a>                           
                                                @endif

                                                <div class="dropdown-divider"></div>

                                                @if($instructor_details->is_verified == INSTRUCTOR_EMAIL_NOT_VERIFIED) 

                                                    <a class="dropdown-item" href="{{ route('admin.instructors.verify', ['instructor_id' => $instructor_details->id]) }}"> {{ tr('verify') }} 
                                                    </a>

                                                @endif 

                                                @if($instructor_details->status == APPROVED)

                                                    <a class="dropdown-item" href="{{ route('admin.instructors.status', ['instructor_id' => $instructor_details->id]) }}" onclick="return confirm(&quot;{{$instructor_details->name}} - {{tr('instructor_decline_confirmation')}}&quot;);" >
                                                        {{ tr('decline') }} 
                                                    </a>

                                                @else
                                                    
                                                    <a class="dropdown-item" href="{{ route('admin.instructors.status', ['instructor_id' => $instructor_details->id]) }}">
                                                        {{ tr('approve') }} 
                                                    </a>
                                                       
                                                @endif

                                                <div class="dropdown-divider"></div>

                                                <a class="dropdown-item" href="{{ route('admin.sub_instructors.create', ['instructor_id' => $instructor_details->id]) }}">
                                                    {{tr('add_sub_instructor')}}
                                                </a>

                                                <a class="dropdown-item" href="{{route('admin.instructors.subscriptions_index',['instructor_id' => $instructor_details->id])}}">{{tr('subscriptions')}}</a>

                                            </div>

                                        </div>

                                    </div>

                                </td>

                            </tr>

                        @endforeach

                    </tbody>
                   
                </table>

                <div class="pull-right">{{ $instructors->appends(request()->input())->links() }}</div>
                
            </div>
            
        </div>
        
    </div>
   
</div>

@endsection