routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        //instructions

        Route::get('instructors', 'AdminController@instructors_index')->name('instructors.index');

        Route::get('instructors/create', 'AdminController@instructors_create')->name('instructors.create');

        Route::get('instructors/edit', 'AdminController@instructors_edit')->name('instructors.edit');

        Route::post('instructors/save', 'AdminController@instructors_save')->name('instructors.save');

        Route::get('instructors/view', 'AdminController@instructors_view')->name('instructors.view');

        Route::get('instructors/delete', 'AdminController@instructors_delete')->name('instructors.delete');

        Route::get('instructors/status', 'AdminController@instructors_status')->name('instructors.status');

        Route::get('instructors/verify', 'AdminController@instructors_verify_status')->name('instructors.verify');

        //sub instructor routes
        Route::get('sub_instructors/create','AdminController@sub_instructors_create')->name('sub_instructors.create');

        Route::post('sub_instructors/save','AdminController@sub_instructors_save')->name('sub_instructors.save');

        Route::get('sub_instructors/delete','AdminController@sub_instructors_delete')->name('sub_instructors.delete');

        //sub instructor subscription
        Route::get('instructor/subscriptions','AdminController@instructors_subscriptions_index')->name('instructors.subscriptions_index');

        Route::post('instructor/subscription_payments','AdminController@instructors_subscriptions_payments')->name('instructors.subscriptions_payments');

        Route::get('instructor/subscriptions_payments/delete','AdminController@instructors_subscriptions_payments_delete')->name('instructors.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        // rooms crud
        Route::get('rooms', 'AdminController@rooms_index')->name('rooms.index');

        Route::get('rooms/create', 'AdminController@rooms_create')->name('rooms.create');

        Route::get('rooms/edit', 'AdminController@rooms_edit')->name('rooms.edit');

        Route::post('rooms/save', 'AdminController@rooms_save')->name('rooms.save');

        Route::get('rooms/view', 'AdminController@rooms_view')->name('rooms.view');

        Route::get('rooms/delete', 'AdminController@rooms_delete')->name('rooms.delete');

        Route::get('rooms/status', 'AdminController@rooms_status')->name('rooms.status');

        //rooms users create
        Route::get('rooms/user/create','AdminController@rooms_user_create')->name('rooms.user.create');

        Route::post('rooms/users/save','AdminController@rooms_user_save')->name('rooms.user.save');

        Route::get('rooms/users/delete','AdminController@rooms_user_delete')->name('rooms.user.delete');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');
    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\AdminLoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Instructor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Setting;

class Instructor extends Model
{
    protected $fillable = ['email', 'password'];

    protected $hidden = ['id'];

    protected $appends = ['instructor_id', 'instructor_unique_id'];

    public function getInstructorIdAttribute() {

        return $this->id;
    }

    public function getInstructorUniqueIdAttribute() {

        return $this->unique_id;
    }

    public function instructorRooms() {

    	return $this->hasMany(Room::class,'instructor_id');
    }

    public function subInstructors() {

    	return $this->hasMany(SubInstructor::class,'sub_instructor_id');
    }

    public function subInstructorDetails() {

        return $this->hasMany(SubInstructor::class,'instructor_id');
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeProfileResponse($query) {

        return $query->select('instructors.*');
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSubInstructorResponse($query) {

        return $query->select(
                'instructors.id',
                'instructors.unique_id',
                'instructors.unique_id as sub_instructor_unique_id', 
                'instructors.name', 
                'instructors.first_name', 
                'instructors.last_name', 
                'instructors.email', 
                'instructors.mobile', 
                'instructors.picture', 
                'instructors.id as sub_instructor_id'
            );
    
    }
      
    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            }

            $model->attributes['payment_mode'] = COD;

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = \Helper::generate_token();

            $model->attributes['token_expiry'] = \Helper::generate_token_expiry();

            $model->attributes['status'] = INSTRUCTOR_APPROVED;

            if(in_array($model->attributes['login_by'], ['facebook', 'google', 'apple', 'linkedin', 'instagram'] )) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['username'] = $model->attributes['unique_id'] = "INS"."-".$model->attributes['id'].routefreestring($model->attributes['name']);

            $model->save();
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = $model->attributes['unique_id'] = "INS"."-".$model->attributes['id'].routefreestring($model->attributes['name']);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            $model->instructorRooms()->delete();

            $model->subInstructors()->delete();

        });

    }
}

app/Subscription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subscription extends Model
{ 
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'plan', 'amount', 'no_of_class', 'no_of_users_each_class'];

    protected $hidden = ['id', 'unique_id'];

    protected $appends = ['subscription_id', 'subscription_unique_id', 'plan_formatted', 'subscription_amount_formatted', 'no_of_class_formatted', 'no_of_users_each_class_formatted', 'currency'];

    public function getSubscriptionIdAttribute() {

        return $this->id;
    }

    public function getSubscriptionUniqueIdAttribute() {

        return $this->unique_id;
    }

    public function getPlanFormattedAttribute() {

        return formatted_plan($this->plan, $this->plan_type);
    }

    public function getSubscriptionAmountFormattedAttribute() {

        return formatted_amount($this->amount);
    }

    public function getNoOfClassFormattedAttribute() {

        return no_of_class_formatted($this->no_of_class);
    }

    public function getNoOfUsersEachClassFormattedAttribute() {

        return no_of_users_each_class_formatted($this->no_of_users_each_class);
    }

    public function getCurrencyAttribute() {

        return \Setting::get('currency' , '$');
    }

    public function subscriptionPayments() {

    	return $this->hasMany(SubscriptionPayment::class,'subscription_id');
    }

    /**
     * Scope a query to only include approved records.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        return $query->where('subscriptions.status', APPROVED);
    
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['unique_id'] = "SI-"."-".uniqid();
        });

        static::created(function($model) {

            $model->attributes['unique_id'] = "SI-"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::deleting(function ($model){

           $model->subscriptionPayments()->delete();

        });
    }
}

resources/views/admin/instructors/subscriptions/index.blade.php
@extends('layouts.admin')

@section('content-header', tr('instructors'))

@section('bread-crumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.instructors.index') }}">{{tr('instructors')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('subscription_history')}}</span>
    </li>
           
@endsection 

@section('content')

<div class="row">

    <div class="col-12">

        <div class="card card card-navy card-outline">

            <div class="card-header">

                <h4 class="text-uppercase">{{tr('subscription_history')}}
                    - <a href="{{route('admin.instructors.view' , ['instructor_id' => $instructor_details->instructor_id ?? 0])}}">{{$instructor_details->name}}</a>
                </h4>

            </div>

            <div class="card-body">

                <table id="table_order" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('payment_id')}}</th>
                            <th>{{tr('subscription')}}</th>
                            <th>{{tr('plan')}}</th>
                            <th>{{tr('amount')}}</th> 
                            <th>{{tr('expiry_date')}}</th>        
                            <th>{{tr('no_of_class')}}</th> 
                            <th>{{tr('no_of_users_each_class')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach($subscripton_payment_history as $i => $payment_details)
                              
                            <tr>
                                <td>{{$i+$subscripton_payment_history->firstItem()}}</td>

                                <td>
                                    <a href="{{route('admin.subscription_payments.view' , ['subscription_payment_id' => $payment_details->id ?? 0])}}">{{$payment_details->payment_id}}</a>
                                </td>

                                <td>
                                    <a href="{{route('admin.subscriptions.view' , ['subscription_id' => $payment_details->subscriptionDetails->id ?? 0])}}"> {{ $payment_details->subscriptionDetails->title ?? '-' }}
                                    </a>
                                </td>

                                <td> {{$payment_details->plan_formatted}} </td>

                                <td>{{$payment_details->subscription_amount_formatted}}</td>

                                <td class="text-danger">{{common_date($payment_details->expiry_date,Auth::guard('admin')->user()->timezone)}}</td>
                                <td>
                                    {{ $payment_details->subscriptionDetails->no_of_class ?? "-" }}
                                </td>

                                <td>
                                    {{ $payment_details->subscriptionDetails->no_of_users_each_class ?? "-" }}
                                </td>

                                <td>     
                                    @if(Setting::get('is_demo_control_enabled') == NO)
                                  
                                        <a class="btn btn-danger" href="{{route('admin.instructors.subscriptions_payments_delete', ['subscription_payment_id' => $payment_details->id])}}" 
                                        onclick="return confirm(&quot;{{tr('subscription_history_delete_confirmation')}}&quot;);">
                                            {{tr('delete')}}
                                        </a>
                                    @endif

                                </td>

                            </tr>

                        @endforeach

                    </tbody>
                   
                </table>

                <div class="pull-right">{{ $subscripton_payment_history->links() }}</div>
                
            </div>
            
        </div>
        
    </div>
   
</div>


<div class="row">

	@foreach($subscriptions as $subscription_details)

		<div class="col-md-3">   

			<div class="card card-danger card-outline">

			   <div class="card-body box-profile">

			      	<h3 class="profile-username text-center text-uppercase">{{$subscription_details->title}}</h3>

			      	<p class="text-muted text-center">{{$subscription_details->plan_formatted}}</p>
			      
				      	<ul class="list-group list-group-unbordered mb-3">

				           	<li class="list-group-item">

				                <b>{{tr('no_of_class')}}</b>

                                <a class="float-right">
                                    {{$subscription_details->no_of_class}}
                                </a>

					        </li>

                            <li class="list-group-item">
                                <b>{{tr('no_of_users_each_class')}}</b> <a class="float-right">{{$subscription_details->no_of_users_each_class}}</a>
                            </li>

					        <li class="list-group-item">
					            <b>{{tr('amount')}}</b> <a class="float-right">{{$subscription_details->subscription_amount_formatted}}</a>
					        </li>
					        
					    </ul>
					<form action="{{route('admin.instructors.subscriptions_payments')}}" method="POST">
						@csrf
						<input type="hidden" name="subscription_id" value="{{$subscription_details->id}}">

						<input type="hidden" name="instructor_id" value="{{Request::get('instructor_id')}}">

						<button class="btn btn-danger btn-block" type="submit" onclick="return confirm('{{tr('do_you_want_to_subscribe_this_plan')}}')">{{tr('subscribe')}}</button>

					</form>

			   </div>

			</div>
	           
	    </div>

    @endforeach

</div>

@endsection