routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        //instructions

        Route::get('instructors', 'AdminController@instructors_index')->name('instructors.index');

        Route::get('instructors/create', 'AdminController@instructors_create')->name('instructors.create');

        Route::get('instructors/edit', 'AdminController@instructors_edit')->name('instructors.edit');

        Route::post('instructors/save', 'AdminController@instructors_save')->name('instructors.save');

        Route::get('instructors/view', 'AdminController@instructors_view')->name('instructors.view');

        Route::get('instructors/delete', 'AdminController@instructors_delete')->name('instructors.delete');

        Route::get('instructors/status', 'AdminController@instructors_status')->name('instructors.status');

        Route::get('instructors/verify', 'AdminController@instructors_verify_status')->name('instructors.verify');

        //sub instructor routes
        Route::get('sub_instructors/create','AdminController@sub_instructors_create')->name('sub_instructors.create');

        Route::post('sub_instructors/save','AdminController@sub_instructors_save')->name('sub_instructors.save');

        Route::get('sub_instructors/delete','AdminController@sub_instructors_delete')->name('sub_instructors.delete');

        //sub instructor subscription
        Route::get('instructor/subscriptions','AdminController@instructors_subscriptions_index')->name('instructors.subscriptions_index');

        Route::post('instructor/subscription_payments','AdminController@instructors_subscriptions_payments')->name('instructors.subscriptions_payments');

        Route::get('instructor/subscriptions_payments/delete','AdminController@instructors_subscriptions_payments_delete')->name('instructors.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        // rooms crud
        Route::get('rooms', 'AdminController@rooms_index')->name('rooms.index');

        Route::get('rooms/create', 'AdminController@rooms_create')->name('rooms.create');

        Route::get('rooms/edit', 'AdminController@rooms_edit')->name('rooms.edit');

        Route::post('rooms/save', 'AdminController@rooms_save')->name('rooms.save');

        Route::get('rooms/view', 'AdminController@rooms_view')->name('rooms.view');

        Route::get('rooms/delete', 'AdminController@rooms_delete')->name('rooms.delete');

        Route::get('rooms/status', 'AdminController@rooms_status')->name('rooms.status');

        //rooms users create
        Route::get('rooms/user/create','AdminController@rooms_user_create')->name('rooms.user.create');

        Route::post('rooms/users/save','AdminController@rooms_user_save')->name('rooms.user.save');

        Route::get('rooms/users/delete','AdminController@rooms_user_delete')->name('rooms.user.delete');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');
    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\AdminLoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Setting, DB;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the UserCard record associated with the user.
     */
    public function userCards() {
        
        return $this->hasMany(UserCard::class, 'user_id');
    }

    public function getSubscribedusers()
    {
        return $this->hasMany(SubscriptionPayment::class, 'user_id', 'id');
    }

    public function roomUserDetails() {

        return $this->hasMany(RoomUser::class, 'user_id');
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.username',
            'users.name',
            'users.email',
            'users.picture',
            'users.mobile',
            'users.address',
            'users.token',
            'users.token_expiry',
            'users.social_unique_id',
            'users.login_by',
            'users.payment_mode',
            'users.status as user_status',
            'users.email_notification_status',
            'users.push_notification_status',
            'users.is_verified',
            'users.user_type',
            'users.registration_steps',
            'users.created_at',
            'users.updated_at'
            );
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOtherResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.username',
            'users.name',
            'users.email',
            'users.picture',
            'users.mobile',
            'users.created_at',
            'users.updated_at'
            );
    
    }
    
    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            }

            $model->attributes['payment_mode'] = COD;

            $model->attributes['username'] = routefreestring($model->attributes['name']);

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = \Helper::generate_token();

            $model->attributes['token_expiry'] = \Helper::generate_token_expiry();

            $model->attributes['status'] = USER_APPROVED;

            if(in_array($model->attributes['login_by'], ['facebook', 'google', 'apple', 'linkedin', 'instagram'] )) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['unique_id'] = "UID"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = routefreestring($model->attributes['name']);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            \Helper::delete_file($model->picture , PROFILE_PATH_USER);

            $model->roomUserDetails()->delete();

        });

    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = \Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = \Helper::generate_email_expiry();

        // Check Email verification controls and email configurations

        if(Setting::get('is_account_email_verification') == YES && Setting::get('is_email_notification') == YES && Setting::get('is_email_configured') == YES) {

            if($model->attributes['login_by'] != 'manual') {

                $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            } else {

                $this->attributes['is_verified'] = USER_EMAIL_NOT_VERIFIED;
            }

        } else { 

            $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;
        }

        return true;
    
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.admin') 

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.users.index') }}">{{tr('users')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_user')}}</span>
    </li>
           
@endsection 

@section('content') 

	@include('admin.users._form') 

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">{{tr('users')}}</a></li>
    
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{ tr('edit_user') }}</span>
    </li>
           
@endsection 

@section('content')

	@include('admin.users._form')

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin') 

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.users.index')}}">{{tr('users')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('view_users') }}</span>
    </li> 
           
@endsection 

@section('content')

<div class="row">

    <div class="col-12">

        <div class="card card-navy card-outline">

            <div class="card-header">

                <h4 class="text-uppercase">{{tr('view_users')}}

                    <a class="btn btn-outline-success pull-right" href="{{route('admin.users.create')}}">
                        <i class="fa fa-plus"></i> {{tr('add_user')}}
                    </a>
              
                </h4>

            </div>

            <div class="card-body">

                <form  action="{{route('admin.users.index')}}" method="GET" role="search">

                    <div class="row">

                        <div class="col-3">
                            @if(Request::has('search_key'))
                                <p class="text-muted">Search results for <b>{{Request::get('search_key')}}</b></p>
                            @endif
                        </div>
                        
                        <div class="col-3">

                            <select class="form-control select2" name="status">

                                <option  class="select-color" value="">{{tr('select_status')}}</option>

                                <option  class="select-color" value="{{SORT_BY_APPROVED}}">{{tr('approved')}}</option>

                                <option  class="select-color" value="{{SORT_BY_DECLINED}}">{{tr('declined')}}</option>

                                <option  class="select-color" value="{{SORT_BY_EMAIL_VERIFIED}}">{{tr('verified')}}</option>

                                <option  class="select-color" value="{{SORT_BY_EMAIL_NOT_VERIFIED}}">{{tr('un_verified')}}</option>

                            </select>

                        </div>

                        <div class="col-6">

                            <div class="input-group">
                                <input type="text" class="form-control" name="search_key"
                                    placeholder="{{tr('users_search_placeholder')}}"> <span class="input-group-btn">
                                    &nbsp

                                    <button type="submit" class="btn btn-default">
                                       <i class="fa fa-search" aria-hidden="true"></i>
                                    </button>

                                    <a class="btn btn-default" href="{{route('admin.users.index')}}"><i class="fa fa-eraser" aria-hidden="true"></i>
                                    </a>
                                </span>
                            </div>

                        </div>

                    </div>

                </form>
                <table id="table_order" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('name')}}</th>
                            <th>{{tr('email')}}</th>
                            <th>{{tr('mobile')}}</th>   
                            <th>{{tr('status')}}</th>
                            <th>{{tr('verify')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $i => $user_details)
                              
                            <tr>
                                <td>{{$i+$users->firstItem()}}</td>

                                <td>
                                    <a href="{{route('admin.users.view' , ['user_id' => $user_details->id])}}"> {{ $user_details->name }}
                                    </a>
                                </td>

                                <td> {{ $user_details->email }} </td>

                                <td> {{ $user_details->mobile ?: tr('unavailable')}} </td>

                                <td>

                                    @if($user_details->status == USER_APPROVED)

                                        <span class="badge bg-success">{{ tr('approved') }} </span>

                                    @else

                                        <span class="badge bg-danger">{{ tr('declined') }} </span>

                                    @endif

                                </td>

                                <td>   

                                    @if($user_details->is_verified == USER_EMAIL_VERIFIED) 

                                        <span class="badge bg-success">{{ tr('verified') }} </span>

                                    @else

                                        <a class="badge bg-info" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> 
                                            {{ tr('verify') }} 
                                        </a>

                                    @endif  
                                                                  
                                </td>

                                <td>     

                                    <div class="template-demo">

                                        <div class="dropdown">

                                            <button class="btn btn-outline-primary  dropdown-toggle" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                {{tr('action')}}
                                            </button>

                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">
                                              
                                                <a class="dropdown-item" href="{{ route('admin.users.view', ['user_id' => $user_details->id]) }}">
                                                    {{tr('view')}}
                                                </a>
                                                
                                                @if(Setting::get('is_demo_control_enabled') == NO)
                                                    <a class="dropdown-item" href="{{ route('admin.users.edit', ['user_id' => $user_details->id]) }}">
                                                        {{tr('edit')}}
                                                    </a>
                                                    
                                                    <a class="dropdown-item" href="{{route('admin.users.delete', ['user_id' => $user_details->id])}}" 
                                                    onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">
                                                        {{tr('delete')}}
                                                    </a>
                                                @else

                                                    <a class="dropdown-item text-muted" href="javascript:;">{{tr('edit')}}</a>
                                                  
                                                    <a class="dropdown-item text-muted" href="javascript:;">{{tr('delete')}}</a>                           
                                                @endif

                                                <div class="dropdown-divider"></div>

                                                @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED) 

                                                    <a class="dropdown-item" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }} 
                                                    </a>

                                                @endif 

                                                @if($user_details->status == USER_APPROVED)

                                                    <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->first_name}} - {{tr('user_decline_confirmation')}}&quot;);" >
                                                        {{ tr('decline') }} 
                                                    </a>

                                                @else
                                                    
                                                    <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
                                                        {{ tr('approve') }} 
                                                    </a>
                                                       
                                                @endif


                                            </div>

                                        </div>

                                    </div>

                                </td>

                            </tr>

                        @endforeach
                    </tbody>
                   
                </table>

                <div class="pull-right" id="paglink">{{ $users->appends(request()->input())->links() }}</div>

            </div>
            
        </div>
       
    </div>
   
</div>


@endsection

resources/views/admin/users/view.blade.php
@extends('layouts.admin') 

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.users.index')}}">{{tr('users')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('view_users') }}</span>
    </li> 
           
@endsection 

@section('content')

<div class="row">

    <div class="col-12">

        <div class="card card-navy card-outline">

            <div class="card-header">

                <h4 class="text-uppercase">{{tr('view_users')}}
                </h4>

            </div>

            <div class="card-body">

            	<div class="row">

	            	<div class="col-md-6">

					    <div class="card card-widget widget-user-2">

					        <div class="widget-user-header">
					            <div class="widget-user-image">
					                <img class="user-image" src="{{$user_details->picture ?: asset('placeholder.jpeg')}}" alt="User Avatar" />
					            </div>
					        </div>

					        @if(Setting::get('is_demo_control_enabled') == NO)

					        	<div class="row">

	                                <div class="col-md-6 align-left">
				                		<a class="btn btn-block btn-outline-secondary" href="{{ route('admin.users.edit', ['user_id' => $user_details->id]) }}">
	                                    {{tr('edit')}}
	                                	</a>
				                	</div>

	                                <div class="col-md-6 align-left">
		                                <a class="btn btn-block btn-outline-danger" href="{{route('admin.users.delete', ['user_id' => $user_details->id])}}" 
		                                onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">
		                                    {{tr('delete')}}
		                                </a>
		                            </div>

	                            </div>

                            @else
                        		<div class="row">
	                            	<div class="col-md-6 align-left">
				                		<a class="btn btn-block btn-outline-secondary" href="user_details:;">{{tr('edit')}}</a>
				                	</div>
				                	<div class="col-md-6 align-left">
				                    	<a class="btn btn-block btn-outline-danger" href="javascript:;" onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">{{tr('delete')}}</a>
				                    </div>
			                    </div>
                                                          
                            @endif

			                <div class="row">

					        	<div class="col-md-6 align-left">

					        		@if($user_details->status == APPROVED)

		                                <a class="btn btn-block btn-outline-danger" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->name}} - {{tr('user_decline_confirmation')}}&quot;);" >
		                                    {{ tr('decline') }} 
		                                </a>

		                            @else
		                                
		                                <a class="btn btn-block btn-outline-success" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
		                                    {{ tr('approve') }} 
		                                </a>
		                                   
		                            @endif
			                	</div>

			                	<div class="col-md-6 align-left">
			                		 @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED) 

                                        <a class="dropdown-item" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }} 
                                        </a>

                                    @endif 
			                    </div>

			                </div>

			                <br>

					    </div>

					</div>

					<div class="col-md-6">
					    
					    <div class="card card-widget widget-user-2">

					        <div class="card-footer p-0">

					            <ul class="nav flex-column">

					            	<li class="nav-item">
					                    <div href="#" class="nav-link">{{tr('name')}} <span class="float-right text-uppercase">{{$user_details->name}}</span> </div>
					                </li>

					            	<li class="nav-item">
					                    <div href="#" class="nav-link">{{tr('email')}}<span class="float-right text-uppercase">{{$user_details->email}}</span> </div>
					                </li>

					                <li class="nav-item">
					                   <div class="nav-link">{{tr('mobile')}}<span class="float-right text-uppercase">{{$user_details->mobile ?: tr('unavailable')}}</span> </div>
					                </li>

					                <li class="nav-item">
					                    <div class="nav-link"> {{tr('payment_mode')}} <span class="float-right badge bg-secondary text-uppercase">{{$user_details->payment_mode}}</span></div>
					                </li>

					                <li class="nav-item">
					                    <div class="nav-link">{{tr('is_verified')}} 
					                    	@if($user_details->is_verified == USER_EMAIL_VERIFIED)
					                    		<span class="float-right badge bg-primary text-uppercase">{{tr('yes')}}</span>
					                    	@else
					                    	 	<span class="float-right badge bg-danger text-uppercase">{{tr('no')}}</span>
					                    	@endif
					                    </div>
					                </li>

					                <li class="nav-item">
					                    <div class="nav-link">{{tr('status')}}
					                    	@if($user_details->status == APPROVED)
					                    		<span class="float-right badge bg-success text-uppercase">{{tr('approved')}}</span>
					                    	@else
					                    	 	<span class="float-right badge bg-danger text-uppercase">{{tr('declined')}}</span>
					                    	@endif 
					                    </div>
					                </li>

					                <li class="nav-item">
					                    <div href="#" class="nav-link">{{tr('device_type')}} <span class="float-right badge bg-info text-uppercase">{{$user_details->device_type}}</span> </div>
					                </li>

					                <li class="nav-item">
					                   <div class="nav-link">{{tr('login_by')}}<span class="float-right text-uppercase">{{$user_details->login_by}}</span></div>
					                </li>


					                <li class="nav-item">
					                    <div class="nav-link">{{tr('created_at')}}<span class="float-right">{{common_date($user_details->created_at,Auth::guard('admin')->user()->timezone)}}</span></div>
					                </li>

					                <li class="nav-item">
					                    <div class="nav-link">{{tr('updated_at')}}<span class="float-right">{{common_date($user_details->updated_at,Auth::guard('admin')->user()->timezone)}}</span></div>
					                </li>

					            </ul>

					        </div>

					    </div>
					   
					</div>

		        </div>

            </div>
            
        </div>
        
    </div>
    
</div>
@endsection