routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        //instructions

        Route::get('instructors', 'AdminController@instructors_index')->name('instructors.index');

        Route::get('instructors/create', 'AdminController@instructors_create')->name('instructors.create');

        Route::get('instructors/edit', 'AdminController@instructors_edit')->name('instructors.edit');

        Route::post('instructors/save', 'AdminController@instructors_save')->name('instructors.save');

        Route::get('instructors/view', 'AdminController@instructors_view')->name('instructors.view');

        Route::get('instructors/delete', 'AdminController@instructors_delete')->name('instructors.delete');

        Route::get('instructors/status', 'AdminController@instructors_status')->name('instructors.status');

        Route::get('instructors/verify', 'AdminController@instructors_verify_status')->name('instructors.verify');

        //sub instructor routes
        Route::get('sub_instructors/create','AdminController@sub_instructors_create')->name('sub_instructors.create');

        Route::post('sub_instructors/save','AdminController@sub_instructors_save')->name('sub_instructors.save');

        Route::get('sub_instructors/delete','AdminController@sub_instructors_delete')->name('sub_instructors.delete');

        //sub instructor subscription
        Route::get('instructor/subscriptions','AdminController@instructors_subscriptions_index')->name('instructors.subscriptions_index');

        Route::post('instructor/subscription_payments','AdminController@instructors_subscriptions_payments')->name('instructors.subscriptions_payments');

        Route::get('instructor/subscriptions_payments/delete','AdminController@instructors_subscriptions_payments_delete')->name('instructors.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        // rooms crud
        Route::get('rooms', 'AdminController@rooms_index')->name('rooms.index');

        Route::get('rooms/create', 'AdminController@rooms_create')->name('rooms.create');

        Route::get('rooms/edit', 'AdminController@rooms_edit')->name('rooms.edit');

        Route::post('rooms/save', 'AdminController@rooms_save')->name('rooms.save');

        Route::get('rooms/view', 'AdminController@rooms_view')->name('rooms.view');

        Route::get('rooms/delete', 'AdminController@rooms_delete')->name('rooms.delete');

        Route::get('rooms/status', 'AdminController@rooms_status')->name('rooms.status');

        //rooms users create
        Route::get('rooms/user/create','AdminController@rooms_user_create')->name('rooms.user.create');

        Route::post('rooms/users/save','AdminController@rooms_user_save')->name('rooms.user.save');

        Route::get('rooms/users/delete','AdminController@rooms_user_delete')->name('rooms.user.delete');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');
    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\AdminLoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin/_logout_model.blade.php
<div class="modal fade" id="logoutModel" tabindex="-1" role="dialog" aria-labelledby="logoutModel" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="logoutModelTitle">{{tr('confirm_logout')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <h5>{{tr('logout_note')}}</h5>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-pill" data-dismiss="modal">{{tr('close')}}</button>
                <a class="btn btn-primary btn-pill" href="{{route('admin.logout')}}">{{tr('logout')}}</a>
            </div>

        </div>

    </div>
    
</div>

resources/views/layouts/admin/focused.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{Setting::get('favicon')}}">

    <title>{{Setting::get('site_name')}}</title>

    <link rel="canonical" href="https://www.wrappixel.com/templates/adminpro/" />

    <!-- Bootstrap Core CSS -->
    <link href="https://www.wrappixel.com/demos/admin-templates/admin-pro/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- page css -->
    <link href="{{asset('admin-assets/css/pages/login-register-lock.css')}}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{asset('admin-assets/css/style.css')}}" rel="stylesheet">
   
</head>

<body class="card-no-border">
   
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">{{Setting::get('site_name')}}</p>
        </div>
    </div>

    @yield('content')
    
    @include('layouts.admin.scripts')
    
</body>

</html>

resources/views/layouts/admin/footer.blade.php
<footer class="main-footer">

<strong>Copyright &copy; {{date('Y')}}  
	<a href="http://adminlte.io">{{Setting::get('site_name' , 'CG-school')}}</a>.</strong>
{{tr('all_right_reserved')}} 
</footer>

resources/views/layouts/admin/header.blade.php
<nav class="main-header navbar navbar-expand navbar-dark navbar-navy">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <img  class="user-image-circle" src="{{ Auth::guard('admin')->user() ? Auth::guard('admin')->user()->picture : asset('placeholder.png') }}" />
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div>
                     <a href="{{route('admin.profile')}}" class="dropdown-item pull-left">{{tr('profile')}}</a>
                </div>
                <div class="dropdown-divider"></div>
                <div>
                     <a class="dropdown-item pull-left" data-toggle="modal" data-target="#logoutModel"> {{tr('logout')}}</a>
                </div>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/admin/scripts.blade.php
<!-- jQuery -->
<script src="{{asset('admin-assets/plugins/jquery/jquery.min.js')}}"></script>

<!-- jQuery UI 1.11.4 -->
<script src="{{asset('admin-assets/plugins/jquery-ui/jquery-ui.min.js')}}"></script>

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>

<!-- Bootstrap 4 -->
<script src="{{asset('admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<!-- ChartJS -->
<script src="{{asset('admin-assets/plugins/chart.js/Chart.min.js')}}"></script>

<!-- JQVMap -->
<script src="{{asset('admin-assets/plugins/jqvmap/jquery.vmap.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>

<!-- jQuery Knob Chart -->
<script src="{{asset('admin-assets/plugins/jquery-knob/jquery.knob.min.js')}}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('admin-assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>

<!-- Summernote -->
<script src="{{asset('admin-assets/plugins/summernote/summernote-bs4.min.js')}}"></script>

<!-- overlayScrollbars -->
<script src="{{asset('admin-assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>

<!-- AdminLTE App -->
<script src="{{asset('admin-assets/dist/js/adminlte.js')}}"></script>

<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('admin-assets/dist/js/pages/dashboard.js')}}"></script>

<!-- AdminLTE for demo purposes -->
<script src="{{asset('admin-assets/dist/js/demo.js')}}"></script>

<!-- DataTables -->
<script src="{{asset('admin-assets/plugins/datatables/jquery.dataTables.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<!-- page script -->
<script>
    
  $(function () {
    
    $('#table_order').DataTable({
        "paging": false,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
    });
  });
</script>

<script type="text/javascript">

    $("#{{$page}}").addClass("active");

    @if(isset($sub_page))
    $("#{{$main_page}}").addClass("menu-open"); 

    $("#{{$sub_page}}").addClass("active"); 
    @endif

    $(document).ready(function() {

        $('.select2').select2();

        $('select').on("select2:close", function () { $(this).focus(); });

        $('.js-example-basic-multiple').select2();

    });

</script>

<!-- daterangepicker -->
<script src="{{asset('admin-assets/daterangepicker/moment.min.js')}}"></script>

<script src="{{asset('admin-assets/daterangepicker/daterangepicker.js')}}"></script>

resources/views/layouts/admin/sidebar.blade.php
<aside class="main-sidebar elevation-4 sidebar-light-navy">

    <a href="{{route('admin.dashboard')}}" class="brand-link navbar-navy">
        <span class="brand-text font-weight-light text-white">{{Setting::get('site_name')}}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{Auth::guard('admin')->user()->picture ?: asset('placeholder.jpeg')}}" class="img-circle elevation-2" alt="User Image" />
            </div>
            <div class="info">
                <a href="" class="d-block">{{Auth::guard('admin')->user()->name ?? "-"}}</a>
            </div>
        </div>
    
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{route('admin.dashboard')}}" class="nav-link" id="dashboard">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            {{tr('dashboard')}}
                        </p>
                    </a>
                </li>

                <li class="nav-header sidebar-header">{{tr('account_management')}}</li>
                
                <li class="nav-item has-treeview" id="users-crud">
                    <a href="#" class="nav-link" id="users">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            {{tr('users')}}
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" >
                        <li class="nav-item">
                            <a href="{{route('admin.users.create')}}" class="nav-link" id="users-create">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('add_user')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.users.index')}}" class="nav-link" id="users-view">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('view_users')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview" id="instructors-crud">
                    <a href="#" class="nav-link" id="instructors">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <p>
                            {{tr('instructors')}}
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" >
                        <li class="nav-item">
                            <a href="{{route('admin.instructors.create')}}" class="nav-link" id="instructors-create">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('add_instructor')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.instructors.index')}}" class="nav-link" id="instructors-view">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('view_instructors')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                
                <li class="nav-header sidebar-header text-uppercase">Meeting Management</li>

                <!-- Room CRUD -->

                <li class="nav-item has-treeview" id="rooms-crud">
                    <a href="#" class="nav-link" id="rooms">
                        <i class="fas fa-home"></i>
                        <p>
                            {{tr('rooms')}}
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" >
                        <li class="nav-item">
                            <a href="{{route('admin.rooms.create')}}" class="nav-link" id="rooms-create">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('add_room')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.rooms.index')}}" class="nav-link" id="rooms-view">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('view_rooms')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview" id="meetings-crud">
                    <a href="#" class="nav-link" id="meetings">
                       <i class="fas fa-handshake"></i>
                        <p>
                            {{tr('meetings')}}
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" >
                        <li class="nav-item">
                            <a href="{{route('admin.meetings.create')}}" class="nav-link" id="meetings-create">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('add_meeting')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.meetings.index')}}" class="nav-link" id="meetings-view">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('view_meetings')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                
                <li class="nav-header sidebar-header">{{tr('revenue_management')}}</li>

                <li class="nav-item has-treeview" id="subscriptions-crud">
                    <a href="#" class="nav-link" id="subscriptions">
                      <i class="fas fa-receipt"></i>
                        <p>
                            {{tr('subscriptions')}}
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" >
                        <li class="nav-item">
                            <a href="{{route('admin.subscriptions.create')}}" class="nav-link" id="subscriptions-create">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('add_subscription')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.subscriptions.index')}}" class="nav-link" id="subscriptions-view">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('view_subscriptions')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview" id="payments-crud">
                    <a href="#" class="nav-link" id="payments">
                      <i class="fab fa-paypal"></i>
                        <p>
                            {{tr('payments')}}
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" >
                        <li class="nav-item">
                            <a href="{{route('admin.revenue.dashboard')}}" class="nav-link" id="revenues-dashboard">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('revenue_dashboard')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.subscription_payments.index')}}" class="nav-link" id="subscription-payments">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{tr('subscription_payments')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-header sidebar-header">{{tr('setting_management')}}</li>

                <li class="nav-item ">
                    <a href="{{route('admin.settings')}}" class="nav-link" id= "settings">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>
                            {{tr('settings')}}
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{route('admin.profile')}}" class="nav-link"  id="profile">
                        <i class="nav-icon fas fa-user-cog"></i>
                        <p>
                            {{tr('profile')}}
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" data-toggle="modal" data-target="#logoutModel"> 
                        <i class="fa fa-share" aria-hidden="true"></i>
                        <p>
                            {{tr('logout')}}
                        </p>
                    </a>
                </li>
                
            </ul>
        </nav>
        
    </div>
   
</aside>